#cloud-config

package_update: true
package_upgrade: true

packages:
  - apache2
  - php
  - php-mysql
  - mysql-server
  - redis-server
  - php-redis
  - unzip

users:
  - name: myuser
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: ""

runcmd:
  # Start services
  - systemctl enable ssh
  - systemctl start ssh
  - systemctl enable apache2
  - systemctl start apache2
  - systemctl enable mysql
  - systemctl start mysql
  - systemctl enable redis-server
  - systemctl start redis-server

  # Download and extract app from GitHub
  - cd /var/www/html
  - wget https://github.com/namer203/webapp/archive/refs/heads/main.zip
  - unzip -o main.zip
  - mv webapp-main/* .
  - rm -rf webapp-main main.zip
  - rm /var/www/html/index.html
  - chown -R www-data:www-data /var/www/html/

# Setup MySQL database and user
  - mysql -e "CREATE DATABASE IF NOT EXISTS igra_app;"
  - mysql -e "CREATE USER IF NOT EXISTS 'igra_user'@'localhost' IDENTIFIED BY '';"
  - mysql -e "GRANT ALL PRIVILEGES ON igra_app.* TO 'igra_user'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"

# Import database
  - mysql -u root igra_app < /var/www/html/db.sql
